name: Push-Images

on:
  release:
    types: [published]
  push:
    branches:    
      - 'actions'
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    env:
      RELEASE: ${{ github.event.release.name }}
    steps:
      - name: get release version
        run: name= ${{env.RELEASE}}; echo version=${name#*Kindling } >> $GITHUB_ENV

      - name: Login Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push grafana image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: kindlingproject/kindling-grafana:latest-alpha
          dst: |
            kindlingproject/kindling-grafana:retag
